# Generated by Django 6.0.2 on 2026-02-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='phone',
        ),
        migrations.AddField(
            model_name='donation',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Claimed', 'Claimed'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
