# Generated by Django 6.0.2 on 2026-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_donation_latitude_donation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
